### PR TITLE
Angler: update blobs from MTC19V

### PR DESCRIPTION
**Pull request by dankoman30**
Change-Id: I617698618fea72b50507943639acdfeb3d383c24

### CODE REVIEW

**Comment by PRJosh** [comment]
Is this good to go?

**Comment by dankoman30** [comment]
tested fine on a dirty build.  might wanna verify with jean first.

my clean build won't be done for a bit.

**Comment by dankoman30** [comment]
i'd say this is all good @PRJosh - you can accept this pull as long as @yank555-lu has no issue

**Comment by yank555-lu** [comment]
Compiling still on my end, but should be good I think. I'll merge it.

**Pull request merged**
